=== emanueledibella/web_systems/html_statico/xml/post.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Post">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Id" type="xs:integer"/>
                <xs:element name="AuthorName" type="xs:string"/>
                <xs:element name="ProfileImage" type="xs:string"/>
                <xs:element name="DateTime" type="xs:dateTime"/>
                <xs:element name="MessageText">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:maxLength value="280"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="MessageImage" type="xs:string" minOccurs="0"/>
                <xs:element name="Likes" type="xs:integer"/>
                <xs:element name="Comments">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Comment" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Id" type="xs:integer"/>
                                        <xs:element name="CommentAuthorName" type="xs:string"/>
                                        <xs:element name="CommentProfileImage" type="xs:string"/>
                                        <xs:element name="CommentDateTime" type="xs:dateTime"/>
                                        <xs:element name="CommentText">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:maxLength value="120"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="CommentImage" type="xs:string" minOccurs="0"/>
                                        <xs:element name="CommentLikes" type="xs:integer"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== emanueledibella/web_systems/src/main/resources/static/xml/2.xml
<?xml version="1.0" encoding="UTF-8"?>
<Post xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="post.xsd">
    <Id>2</Id>
    <AuthorName>Matt Tizio</AuthorName>
    <ProfileImage>https://randomuser.me/api/portraits/men/3.jpg</ProfileImage>
    <DateTime>2024-11-01T10:25:00</DateTime>
    <PostTitle>Titolo 2</PostTitle>
    <MessageText>Post di test!</MessageText>
    <MessageImage>https://picsum.photos/200/300?random=2</MessageImage>
    <Likes>8</Likes>
    <Comments>
        <Comment>
            <Id>3</Id>
            <CommentAuthorName>Jane Smith</CommentAuthorName>
            <CommentProfileImage>https://randomuser.me/api/portraits/women/1.jpg</CommentProfileImage>
            <CommentDateTime>2024-11-01T11:00:00</CommentDateTime>
            <CommentText>Bravo Matt!</CommentText>
            <CommentImage>https://picsum.photos/200/300?random=3</CommentImage>
            <CommentLikes>1</CommentLikes>
        </Comment>
        <Comment>
            <Id>4</Id>
            <CommentAuthorName>Mike Jones</CommentAuthorName>
            <CommentProfileImage>https://randomuser.me/api/portraits/men/2.jpg</CommentProfileImage>
            <CommentDateTime>2024-11-04T11:05:00</CommentDateTime>
            <CommentText>Sciao belo!</CommentText>
            <CommentLikes>0</CommentLikes>
        </Comment>
    </Comments>
</Post>

=== emanueledibella/web_systems/src/main/resources/static/xml/3.xml
<?xml version="1.0" encoding="UTF-8"?>
<Post xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="post.xsd">
    <Id>3</Id>
    <AuthorName>Mario Rossi</AuthorName>
    <ProfileImage>https://randomuser.me/api/portraits/men/4.jpg</ProfileImage>
    <DateTime>2024-11-04T09:00:00</DateTime>
    <PostTitle>Titolo 3</PostTitle>
    <MessageText>Ciao a tutti! Sono felice di iniziare questa nuova avventura qui! Spero di condividere tanti momenti speciali con voi e di imparare molto da questa esperienza. Grazie per il benvenuto!</MessageText>
    <MessageImage>https://picsum.photos/200/300?random=4</MessageImage>
    <Likes>45</Likes>
    <Comments>
        <Comment>
            <Id>5</Id>
            <CommentAuthorName>Luca Verdi</CommentAuthorName>
            <CommentProfileImage>https://randomuser.me/api/portraits/men/5.jpg</CommentProfileImage>
            <CommentDateTime>2024-11-04T09:30:00</CommentDateTime>
            <CommentText>Benvenuto, Mario! Non vedo l'ora di vedere i tuoi post!</CommentText>
            <CommentImage>https://picsum.photos/200/300?random=5</CommentImage>
            <CommentLikes>12</CommentLikes>
        </Comment>
        <Comment>
            <Id>6</Id>
            <CommentAuthorName>Sara Bianchi</CommentAuthorName>
            <CommentProfileImage>https://randomuser.me/api/portraits/women/3.jpg</CommentProfileImage>
            <CommentDateTime>2024-11-04T09:45:00</CommentDateTime>
            <CommentText>Piacere di conoscerti, Mario!</CommentText>
            <CommentLikes>8</CommentLikes>
        </Comment>
    </Comments>
</Post>

=== emanueledibella/web_systems/src/main/resources/static/xml/1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Post xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="post.xsd">
    <Id>1</Id>
        <AuthorName>John Doe</AuthorName>
        <ProfileImage>https://randomuser.me/api/portraits/men/1.jpg</ProfileImage>
        <DateTime>2024-11-04T10:30:00</DateTime>
        <PostTitle>Titolo 1</PostTitle>
        <MessageText>This is my first post on this platform!</MessageText>
        <MessageImage>https://picsum.photos/200/300</MessageImage>
        <Likes>20</Likes>
        <Comments>
            <Comment>
                <Id>1</Id>
                <CommentAuthorName>Jane Smith</CommentAuthorName>
                <CommentProfileImage>https://randomuser.me/api/portraits/women/1.jpg</CommentProfileImage>
                <CommentDateTime>2024-11-04T11:00:00</CommentDateTime>
                <CommentText>Great post, John!</CommentText>
                <CommentImage>https://picsum.photos/200/300?random=1</CommentImage>
                <CommentLikes>5</CommentLikes>
            </Comment>
            <Comment>
                <Id>2</Id>
                <CommentAuthorName>Mike Jones</CommentAuthorName>
                <CommentProfileImage>https://randomuser.me/api/portraits/men/2.jpg</CommentProfileImage>
                <CommentDateTime>2024-11-04T11:05:00</CommentDateTime>
                <CommentText>Welcome to the platform!</CommentText>
                <CommentLikes>3</CommentLikes>
            </Comment>
        </Comments>
</Post>
